AWSTemplateFormatVersion: '2010-09-09'
Description: Cross account deployment test

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-cross-account-bucket-sychov-123
